#  +-------------------------------------------------------------------------------------+
#  |    _____   _       _____   _   _    ___    _____    ___    ____    ______           |
#  |   |  ___| | |     |  ___| | | | |  / _ \  |_   _|  / _ \  |  _ \  /  ___/    _      |
#  |   | |___  | |     | |___  | | | | | |_| |   | |   | | | | | |_| | | |___   _| |_    |
#  |   |  ___| | |     |  ___| |  -  | |  _  |   | |   | | | | |    /  |___  | |_ + _|   |
#  |   | |___  | |___  | |___   \   /  | | | |   | |   | |_| | | |\ \   ___| |   |_|     |
#  |   |_____| |_____| |_____|   \_/   |_| |_|   |_|    \___/  |_| \_\ /_____/           |
#  |                                                                                     |
#  |                                                                                     |
#  |   Author: SoKnight                                                 Version: 2.0.0   |
#  +-------------------------------------------------------------------------------------+
#   
# Useful resources:
# - Available material-types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# - Available sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#
# Configuration of database
database:
  # Should plugin use SQLite Database as data storage?
  # Specify 'true' for SQLite or 'false' for MySQL
  use-sqlite: true
  # MySQL configuration
  host: localhost
  port: 3306
  name: elevatorsplus
  user: admin
  password: eplus
  # SQLite configuration
  file: database.db

# Configuration of messages
messages:
  # Messages localization, available: [en, ru]
  # Write in discussion on spigotmc plugin page, if you can translate plugin to other languages
  locale: en
  # Should plugin view debug messages to console
  debug: false
  # Count of strings on one list page for '/ep .. list' commands
  list-size: 10

#  _____   +----------------------------------------+
# |_|_|_|     $ Default height for every floor.
#    *       For example, there floor height is 3,
#    *       because between two levels located
#  __*__     three any blocks. Therefore floor
# |_|_|_|    height is distance between two levels.
#          +----------------------------------------+
# You can set custom height for every floor using this command:
# /eplus modify <elevator> floorheight <floor> <height>
default-floor-height: 3

# Amount of levels which be added or removed from total level specified for callbutton
# For example: when player with active selection session toggle-on shift and try break button,
# linked level (floor) value of this button will be decreased on specified below value
# And if this player also try click right mouse button on the button, button level value
# will be also increased on specified below value. Without shift this value is 1
shift-linked-level-value: 3

# True: control can be destroyed without automaticly unlinking from their elevator
# False: if control will be destroyed, it will be unlinked from their elevator automaticly
# For this actions player-destroyer must has permission 'eplus.controls.destroy'
#
# Notice: this feature as disabled is heavy for server perfomance and if your server is
# running on weak hardware, you don't should disable this parameter
allow-controls-destroy: false

# Configuration of elevator controls
controls: 
  # Use this parameter is you want change blocks of call-button
  # Simply add new or delete the current materials
  call-buttons: [stone_button]
  # Use this parameter is you want change types of sign
  # Simply add new or delete the current materials
  signs: [oak_wall_sign, birch_wall_sign]
  # You can change strings on signs, also using color codes
  # Also you can use placeholders: [%name%, %current_level%, %max_level%]
  sign-content:
  - '&l[Elevators+]'
  - 'Elevator: &1%name%'
  - 'Level: &1%cur_level%&0/&1%max_level%'
  - 'Click to open menu'

# Configuration of automaticly opening doors nearby
# Plugin can scan around doors and open that 
# when elevator will reach needed floor
open-doors: 
  # Feature is enabled
  enabled: true
  # List of doors material types
  doors: [iron_door]

# Configuration of playing sounds
sound-playing:
  # Playing sound when elevator reach needed floor
  complete:
    # Playing is enabled
    enabled: true
    # Name of sound which will be played
    sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
    # Volume of sound
    volume: 80
  # Playing sounds when elevator start moving
  starting:
    enabled: true
    sound: 'ENTITY_MINECART_RIDING'
    volume: 80
  # Playing sounds when user change controls
  selection:
    enabled: true
    sound: 'BLOCK_TRIPWIRE_ATTACH'
    volume: 40

# Configuration of floors menu
gui:
  # Name of inventory window
  # Tip: use %name% to insert name of elevator
  title: "Elevator %name%"
  # Size of menu inventory
  # Tip: specify 0 to autosize (by amount of floors)
  size: 0
  # Configuration of current floor icon
  current:
    # Displayname of icon
    name: "&aLevel %level%"
    # Lore of icon
    lore:
    - ''
    - ' &aCurrent floor '
    - ''
    # Item will has glowing effect (will be enchanted) or not
    enchanted: true
    # Material type of icon
    material: 'lime_stained_glass_pane'
  # Configuration of available floor icon
  other:
    name: "&7Level %level%"
    lore:
    - ''
    - ' &8Click to move '
    - ''
    enchanted: false
    material: 'gray_stained_glass_pane'